project:
  type: website
  output-dir: docs

website:
  title: "yliu566.github.io"
  site-url: https://yliu566.github.io/
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yliu566
#      - icon: linkedin
#        href: 
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

comments:
  utterances:
    repo: yliu566/yliu566.github.io

execute:
  freeze: auto