project:
  type: website

website:
  title: "yliu566.github.io"
  site-url: https://yliu566.github.io/
  google-analytics: ""
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yliu566
#      - icon: linkedin
#        href: 
#      - icon: rss
#        href: blog.xml
format:
  html:
    theme: cosmo
    css: styles.css



